### ISSUE TITLE
Script checks for /etc writable permission even if /etc directory is not used

### ISSUE THREAD

**Issue by electrofloat** [wirefalls/geo-nft#30]
I was just trying out the script without sudo of course by modifying the variables:
`geo_conf, errorlog, base_dir`

but even if /etc would not be used in this scenario the script still checks for it here:
https://github.com/wirefalls/geo-nft/blob/main/geo-nft.sh#L1056

**Comment by wirefalls** [comment]
> I was just trying out the script without sudo of course by modifying the variables: `geo_conf, errorlog, base_dir`
> 
> but even if /etc would not be used in this scenario the script still checks for it here: https://github.com/wirefalls/geo-nft/blob/main/geo-nft.sh#L1056

That's a good catch, I'll work on a fix. Thanks.

**Comment by wirefalls** [comment]
Hello,

I'll be pushing a fix for this shortly. Thank you for finding and reporting the issue, very much appreciated.
