### ISSUE TITLE
Using netdev, allow outbound initiated

### ISSUE THREAD

**Issue by lingfish** [wirefalls/geo-nft#33]
Thanks heaps for this project, it's awesome.

I'm using `netdev` for inbound country blocks only.  I'm noticing more and more that my systems want to connect to a country I'm banning, and so when the initial reply comes back, it's blocked at the `netdev` family.  Of course, `netdev` doesn't know `ct state` so... is the only option to give up `netdev` and move inbound blocks to `inet`?

**Comment by cdev-tux** [comment]
Thank you. If you want to allow outgoing traffic to a given country but block new incoming traffic from that same country then I believe you’ll want to create your incoming rule to block that traffic in the inet table. I don’t know of a way around that. I hope that helps.

**Comment by wirefalls** [comment]
Thank you. If you want to allow outgoing traffic to a given country but block new incoming traffic from that same country then I believe you'll want to create your incoming rule to block that traffic in the inet table. I don't know of a way around that. I hope that helps. If you have any further questions you can use the discussions tab at the top of the page. Thanks.
