### ISSUE TITLE
No refill-sets.conf or nft files

### ISSUE THREAD

**Issue by sandroshu** [wirefalls/geo-nft#35]
refill-sets.conf is missing after running the script on Ubuntu 22.04

If I create it manually the .nft is not being created.

If I set refill reload it is looking for it in the wrong place(?) /etc/nftables/geo-nft//etc/nftables/geo-nft/
(according to the error it printed)

**Comment by wirefalls** [comment]
Hello,

I'll need to do some additional testing here but I've been able to verify the issue. There are a few things that may be preventing the refill-sets.conf file from generating. Make sure that nftables is enabled and active, otherwise the file may not be created. You can check the status with:

	systemctl status nftables

The other issue is shown in pull request #32.

The pathname of the nft program needs to be determined at run time instead of being hard coded in the script. I'm working on this now and I'll have an update after testing.

Thanks

**Comment by wirefalls** [comment]
Hello,

Please test the latest code and let me know if it solves your issue. Thank you.

**Comment by wirefalls** [comment]
I'm going to close this issue. Feel free to reopen it if you are still having problems. Thanks.

**Comment by yeazzzz** [comment]
Ubuntu 18.04.6 LTS
nft -v
nftables v0.8.2 (Joe Btfsplk)

when i sudo geo-nft has some err happen:

Checking for settings in /etc/nftables/geo-nft/refill-sets.conf

geo-nft.sh v2.2.10:
        The following 'define-ipv4' line in /etc/nftables/geo-nft/refill-sets.conf
        does not point to a valid nftables set defined in your main ruleset (nftables.conf):
        define-ipv4 netdev filter geo-netdev4 AD,BI

Invalid settings were found in 'refill-sets.conf'.
Automatic generation of /etc/nftables/geo-nft/refill-sets.nft will be skipped.


refill-sets.nft:
# Refill-sets configuration file
# Generated by geo-nft.sh v2.2.10
# Automatically flush and refill geolocation sets.
# The refill-sets.nft nftables script will be
# auto-generated using information provided here.
# Uncomment any settings below and modify as needed.
# Comment out all lines to disable this feature (default).


# Specify 'include' lines to add to refill-sets.nft.
# You can add as many include lines as required.
# ==============================================
include "/etc/nftables/geo-nft/include-all.ipv4"
include "/etc/nftables/geo-nft/include-all.ipv6"
#include "/etc/nftables/geo-nft/countrysets/*"


# Specify which sets to flush and fill with refill-sets.nft.
# Sets should be defined (without elements) in nftables.conf.
# Use 'define-ipv4' or 'define-ipv6' at the beginning of each
# line to define the IP address type. There should be 5 fields
# on each line separated by spaces. Multiple country codes
# should be comma separated without spaces between codes as
# shown below.
#
# Define-Protocol   Table Family   Table Name   Set Name   Country Codes To Fill Set
# ==================================================================================
# For 'netdev' table uncomment either or both of the following:
define-ipv4 netdev filter geo-netdev4 AD,BI
define-ipv6 netdev filter geo-netdev6 AQ,BI

# For 'inet' table (IPv4-IPv6) uncomment either or both of the following:
define-ipv4 inet filter geo-inet4 AD
define-ipv6 inet filter geo-inet6 AQ

# For 'ip' table (IPv4 only) uncomment the following:
# define-ipv4 ip filter geo-ip4 AD

# For 'ip6' table (IPv6 only) uncomment the following:
#define-ipv6 ip6 filter geo-ip6 AD

# Add any additional 'define-ipv4' or 'define-ipv6' lines here:

**Comment by yeazzzz** [comment]
Ubuntu 18.04.6 LTS
nft -v
nftables v0.8.2 (Joe Btfsplk)

when i sudo geo-nft has some err happen:

Checking for settings in /etc/nftables/geo-nft/refill-sets.conf

geo-nft.sh v2.2.10:
The following 'define-ipv4' line in /etc/nftables/geo-nft/refill-sets.conf
does not point to a valid nftables set defined in your main ruleset (nftables.conf):
define-ipv4 netdev filter geo-netdev4 AD,BI

Invalid settings were found in 'refill-sets.conf'.
Automatic generation of /etc/nftables/geo-nft/refill-sets.nft will be skipped.

refill-sets.nft:

# Define-Protocol   Table Family   Table Name   Set Name   Country Codes To Fill Set
# ==================================================================================
# For 'netdev' table uncomment either or both of the following:
define-ipv4 netdev filter geo-netdev4 AD,BI
define-ipv6 netdev filter geo-netdev6 AQ,BI

# For 'inet' table (IPv4-IPv6) uncomment either or both of the following:
define-ipv4 inet filter geo-inet4 AD
define-ipv6 inet filter geo-inet6 AQ

# For 'ip' table (IPv4 only) uncomment the following:
#define-ipv4 ip filter geo-ip4 AD

# For 'ip6' table (IPv6 only) uncomment the following:
#define-ipv6 ip6 filter geo-ip6 AD

# Add any additional 'define-ipv4' or 'define-ipv6' lines here:

**Comment by yeazzzz** [comment]
Ubuntu 18.04.6 LTS
nft -v
nftables v0.8.2 (Joe Btfsplk)

when i sudo geo-nft has some err happen:

Checking for settings in /etc/nftables/geo-nft/refill-sets.conf

geo-nft.sh v2.2.10:
The following 'define-ipv4' line in /etc/nftables/geo-nft/refill-sets.conf
does not point to a valid nftables set defined in your main ruleset (nftables.conf):
define-ipv4 netdev filter geo-netdev4 AD,BI

Invalid settings were found in 'refill-sets.conf'.
Automatic generation of /etc/nftables/geo-nft/refill-sets.nft will be skipped.

refill-sets.nft:
`# Refill-sets configuration file
# Generated by geo-nft.sh v2.2.10
# Automatically flush and refill geolocation sets.
# The refill-sets.nft nftables script will be
# auto-generated using information provided here.
# Uncomment any settings below and modify as needed.
# Comment out all lines to disable this feature (default).


# Specify 'include' lines to add to refill-sets.nft.
# You can add as many include lines as required.
# ==============================================
include "/etc/nftables/geo-nft/include-all.ipv4"
include "/etc/nftables/geo-nft/include-all.ipv6"
#include "/etc/nftables/geo-nft/countrysets/*"


# Specify which sets to flush and fill with refill-sets.nft.
# Sets should be defined (without elements) in nftables.conf.
# Use 'define-ipv4' or 'define-ipv6' at the beginning of each
# line to define the IP address type. There should be 5 fields
# on each line separated by spaces. Multiple country codes
# should be comma separated without spaces between codes as
# shown below.
#
# Define-Protocol   Table Family   Table Name   Set Name   Country Codes To Fill Set
# ==================================================================================
# For 'netdev' table uncomment either or both of the following:
define-ipv4 netdev filter geo-netdev4 AD,BI
define-ipv6 netdev filter geo-netdev6 AQ,BI

# For 'inet' table (IPv4-IPv6) uncomment either or both of the following:
define-ipv4 inet filter geo-inet4 AD
define-ipv6 inet filter geo-inet6 AQ

# For 'ip' table (IPv4 only) uncomment the following:
# define-ipv4 ip filter geo-ip4 AD

# For 'ip6' table (IPv6 only) uncomment the following:
#define-ipv6 ip6 filter geo-ip6 AD

# Add any additional 'define-ipv4' or 'define-ipv6' lines here:
`

**Comment by yeazzzz** [comment]
```
# Refill-sets configuration file
# Generated by geo-nft.sh v2.2.10
# Automatically flush and refill geolocation sets.
# The refill-sets.nft nftables script will be
# auto-generated using information provided here.
# Uncomment any settings below and modify as needed.
# Comment out all lines to disable this feature (default).


# Specify 'include' lines to add to refill-sets.nft.
# You can add as many include lines as required.
# ==============================================
include "/etc/nftables/geo-nft/include-all.ipv4"
include "/etc/nftables/geo-nft/include-all.ipv6"
#include "/etc/nftables/geo-nft/countrysets/*"


# Specify which sets to flush and fill with refill-sets.nft.
# Sets should be defined (without elements) in nftables.conf.
# Use 'define-ipv4' or 'define-ipv6' at the beginning of each
# line to define the IP address type. There should be 5 fields
# on each line separated by spaces. Multiple country codes
# should be comma separated without spaces between codes as
# shown below.
#
# Define-Protocol   Table Family   Table Name   Set Name   Country Codes To Fill Set
# ==================================================================================
# For 'netdev' table uncomment either or both of the following:
define-ipv4 netdev filter geo-netdev4 AD,BI
define-ipv6 netdev filter geo-netdev6 AQ,BI

# For 'inet' table (IPv4-IPv6) uncomment either or both of the following:
define-ipv4 inet filter geo-inet4 AD
define-ipv6 inet filter geo-inet6 AQ

# For 'ip' table (IPv4 only) uncomment the following:
# define-ipv4 ip filter geo-ip4 AD

# For 'ip6' table (IPv6 only) uncomment the following:
#define-ipv6 ip6 filter geo-ip6 AD

# Add any additional 'define-ipv4' or 'define-ipv6' lines here:

```

**Comment by yeazzzz** [comment]
Ubuntu 18.04.6 LTS
nft -v
nftables v0.8.2 (Joe Btfsplk)

when i sudo geo-nft has some err happen:

Checking for settings in /etc/nftables/geo-nft/refill-sets.conf

geo-nft.sh v2.2.10:
The following 'define-ipv4' line in /etc/nftables/geo-nft/refill-sets.conf
does not point to a valid nftables set defined in your main ruleset (nftables.conf):
define-ipv4 netdev filter geo-netdev4 AD,BI

Invalid settings were found in 'refill-sets.conf'.
Automatic generation of /etc/nftables/geo-nft/refill-sets.nft will be skipped.

refill-sets.nft:
```
# Refill-sets configuration file
# Generated by geo-nft.sh v2.2.10
# Automatically flush and refill geolocation sets.
# The refill-sets.nft nftables script will be
# auto-generated using information provided here.
# Uncomment any settings below and modify as needed.
# Comment out all lines to disable this feature (default).


# Specify 'include' lines to add to refill-sets.nft.
# You can add as many include lines as required.
# ==============================================
include "/etc/nftables/geo-nft/include-all.ipv4"
include "/etc/nftables/geo-nft/include-all.ipv6"
#include "/etc/nftables/geo-nft/countrysets/*"


# Specify which sets to flush and fill with refill-sets.nft.
# Sets should be defined (without elements) in nftables.conf.
# Use 'define-ipv4' or 'define-ipv6' at the beginning of each
# line to define the IP address type. There should be 5 fields
# on each line separated by spaces. Multiple country codes
# should be comma separated without spaces between codes as
# shown below.
#
# Define-Protocol   Table Family   Table Name   Set Name   Country Codes To Fill Set
# ==================================================================================
# For 'netdev' table uncomment either or both of the following:
define-ipv4 netdev filter geo-netdev4 AD,BI
define-ipv6 netdev filter geo-netdev6 AQ,BI

# For 'inet' table (IPv4-IPv6) uncomment either or both of the following:
define-ipv4 inet filter geo-inet4 AD
define-ipv6 inet filter geo-inet6 AQ

# For 'ip' table (IPv4 only) uncomment the following:
# define-ipv4 ip filter geo-ip4 AD

# For 'ip6' table (IPv6 only) uncomment the following:
#define-ipv6 ip6 filter geo-ip6 AD

# Add any additional 'define-ipv4' or 'define-ipv6' lines here:
```

**Comment by wirefalls** [comment]
Hello,

You replied to a closed issue. Can you please open up a new discussion so that we can try to diagnose the issue you're having? Here's the link to the Discussions: https://github.com/wirefalls/geo-nft/discussions/new?category=general

Thank you

**Comment by yeazzzz** [comment]
> I'm going to close this issue. Feel free to reopen it if you are still having problems. Thanks.

ok
